<a href="https://colab.research.google.com/github/tadtapong/tadtapong.github.io/blob/main/Mathematics_for_AI_%5BFundamental%5D_(MAT1001).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Matrix Multiplication

In [3]:
import numpy as np

In [10]:
a = [[1, 1],
    [2, 2]]
b = [[2, 2,],
    [3, 3]]
a = np.array(a)
b = np.array(b)
print(a)
print(b)
print(a.dot(b))

[[1 1]
 [2 2]]
[[2 2]
 [3 3]]
[[ 5  5]
 [10 10]]


##Linear Transformation